/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "printer.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	// step 1. execute the SVC instruction with an argument
	__asm("SVC #0x08");

    /* Loop forever */
	for(;;);
}



__attribute__ ((naked)) SVC_Handler() {
	// same as before, we write a naked function to catch the MSP
	// address with no modification
	__asm("MRS R0, MSP");
	// as per the procedure call standard for the arm architecture, r0 is passed as the first argument for the branch call
	__asm("B SVC_Handler_C");
}


void SVC_Handler_C(uint32_t *pBaseOfStack) {
	// use printer:
	char buffer[50];
	snprintf(buffer, sizeof(buffer), "in the SVC handler\n");
	ITM_SendString(buffer);

	uint8_t *pReturn_address = (uint32_t*)pBaseOfStack[6];

	// step 2. decrement the return address by 2 to get the op code of the SVC instruction
	pReturn_address -= 2;

	// step 3. extract the SVC number (LSB of the op code)
	uint8_t svc_number = *pReturn_address;

	snprintf(buffer, sizeof(buffer), "svc_number: %d\n", svc_number);
	ITM_SendString(buffer);
}
