/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "printer.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint32_t *pSHCSR_ADDRESS = (uint32_t*) 0xE000ED24; // System Handler Control and State Register
uint32_t *pUFSR_ADDRESS = (uint32_t*) 0xE000ED2A; // Usage Fault Status Register
uint32_t *pCCR_ADDRESS = (uint32_t*) 0xE000ED14; // Configuration and Control Register


int divide(int x, int y);

int main(void) {

	// step 1. enable all configurable faults
	// usage fault, memory management fault and bus fault
	*pSHCSR_ADDRESS |= (1 << 16); // UsageFault enable bit
	*pSHCSR_ADDRESS |= (1 << 17); // BusFault enable bit,
	*pSHCSR_ADDRESS |= (1 << 18); // MemManage enable bit,

	// step 2. enable divide by zero trap in the Configuration and Control Register
	*pCCR_ADDRESS |= (1 << 4);  // enable the divide by zero trap

	// step 3. attempt to divide by zero
	divide(1, 0);

	/* Loop forever */
	for (;;);
}

// step 2. implement the fault handlers
void HardFault_Handler() {
	printf("exception in hard fault\n");
	while (1)
		;
}

void MemManage_Handler() {
	printf("exception in MemManage_Handler\n");
	while (1);
}
void BusFault_Handler() {
	printf("exception in BusFault_Handlern");
	while (1);
}

__attribute__((naked)) void UsageFault_Handler() {
	__asm ("MRS r0, MSP");
	__asm ("B UsageFault_Handler_C");

}

void UsageFault_Handler_C(uint32_t *pBaseStackFrame) {
	// use printer:
	char buffer[50];
	snprintf(buffer, sizeof(buffer), "exception in UsageFault_Handler\n");
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "USFR: %lx\n", (*pUFSR_ADDRESS) & 0xFFFF);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "pBaseStackFrame: %p\n", pBaseStackFrame);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or r0: %lx\n", pBaseStackFrame[0]);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or r1: %lx\n", pBaseStackFrame[1]);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or r2: %lx\n", pBaseStackFrame[2]);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or r3: %lx\n", pBaseStackFrame[3]);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or r12: %lx\n", pBaseStackFrame[4]);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or LR: %lx\n", pBaseStackFrame[5]);
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or PC: %lx\n", pBaseStackFrame[6]); // Program Counter
	ITM_SendString(buffer);

	snprintf(buffer, sizeof(buffer), "value or xPSR: %lx\n",
			pBaseStackFrame[7]);  // Program Status Register
	ITM_SendString(buffer);

	while (1);
}


int divide(int x, int y) {
	return x / y;
}

